settings: do not use schema for Store
Using a schema causes avj to validate the schema passed into the
store, but as we use non-standardized key names, it will fail
the strict check.

Pass in options instead of a schema, as these do not get strictly
validated.

This is in preparation to update to a new version of electron-store
which updates avj and triggers this issue:

-----

A JavaScript error occurred in the main process
Uncaught Exception:
Error: strict mode: unknown keyword: "opencuts"
    at checkStrictMode (/android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/compile/util.js:174:15)
    at checkUnknownRules (/android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/compile/util.js:32:13)
    at alwaysValidSchema (/android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/compile/util.js:19:5)
    at /android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/vocabularies/applicator/properties.js:23:81
    at Array.filter (<anonymous>)
    at Object.code (/android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/vocabularies/applicator/properties.js:23:37)
    at keywordCode (/android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/android/halium/projects/ubports-installer/node_modules/conf/node_modules/ajv/dist/compile/codegen/index.js:568:18)

-----

Change-Id: Ib7ae997611697cc0c91d4da84e117f78e0f2a1c5
Signed-off-by: Alexander Martinz <amartinz@shiftphones.com>